apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ros-backend
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ros-tenant/ros-backend/ros-backend@sha256:56b3cdbfc28562edf3a0c3e801a14b3c201d5070b5bc784a33e480fefacf5f27
        name: container-image
        resources: {}
status: {}
