apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ros-backend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ros-backend
    app.kubernetes.io/part-of: ros-backend
  name: ros-backend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ros-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ros-backend
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ros-tenant/ros-backend/ros-backend@sha256:56b3cdbfc28562edf3a0c3e801a14b3c201d5070b5bc784a33e480fefacf5f27
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
